// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxe5_mwKPOesxNzpHf65aeq6XG5Tg_kZk',
    appId: '1:964877342939:web:087c1b916a61fa086e14fe',
    messagingSenderId: '964877342939',
    projectId: 'read-in-1b0d3',
    authDomain: 'read-in-1b0d3.firebaseapp.com',
    storageBucket: 'read-in-1b0d3.appspot.com',
    measurementId: 'G-D76CMD4XXF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSFUfjaU7fYiJtmWsSPS4CkVgF2vWl5tw',
    appId: '1:964877342939:android:117b62e15f2134a16e14fe',
    messagingSenderId: '964877342939',
    projectId: 'read-in-1b0d3',
    storageBucket: 'read-in-1b0d3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1NdsVwiS9E79sUrs1nUtbYTudHHKwlgg',
    appId: '1:964877342939:ios:9691a704473c93196e14fe',
    messagingSenderId: '964877342939',
    projectId: 'read-in-1b0d3',
    storageBucket: 'read-in-1b0d3.appspot.com',
    iosClientId: '964877342939-tgnc5qn0efno9mai29flb4tsh8ficura.apps.googleusercontent.com',
    iosBundleId: 'com.example.readIn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1NdsVwiS9E79sUrs1nUtbYTudHHKwlgg',
    appId: '1:964877342939:ios:d1e00b0a01b155be6e14fe',
    messagingSenderId: '964877342939',
    projectId: 'read-in-1b0d3',
    storageBucket: 'read-in-1b0d3.appspot.com',
    iosClientId: '964877342939-he3v39fc72mdja7erns9ocmpqe9qbb1p.apps.googleusercontent.com',
    iosBundleId: 'com.example.readIn.RunnerTests',
  );
}
